apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  {{- if .Values.cloudCredentialSecretName }}
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  {{- end }}
  kubernetesVersion: v1.24.17+rke2r1
  rkeConfig:
    chartValues:
      rke2-calico: {}
      rancher-vsphere-cpi:
        vCenter:
          datacenters: DC01_Local
          host: 172.29.192.20
          password: vCenter.password
          username: vCenter.user
      rancher-vsphere-csi:
        storageClass:
          datastoreURL: ds:///vmfs/volumes/5cbaab2e-f0847b38-f712-0cc47adc3c62/
        vCenter:
          datacenters: DC01_Local
          host: 172.29.192.20
          password: vCenter.password
          username: vCenter.user
    machineSelectorConfig:
      - config:
          cloud-provider-name: rancher-vsphere
          protect-kernel-defaults: false
          system-default-registry: {{ .Values.registry.privateRegistryURL }}
    registries:
      configs:
        {{ .Values.registry.privateRegistryURL }}:
          authConfigSecretName: {{ .Values.registry.privateRegistrySecret }}
          insecureSkipVerify: false
      mirrors:
        {}
    machinePools:
    - controlPlaneRole: true
      etcdRole: true
      machineConfigRef:
        kind: VmwarevsphereConfig
        name: {{ .Values.cluster.name }}-master
      machineOS: linux
      name: master
      quantity: {{ .Values.nodepool.mastercount }}
      unhealthyNodeTimeout: 0s
    - machineConfigRef:
        kind: VmwarevsphereConfig
        name: {{ .Values.cluster.name }}-worker
      machineOS: linux
      name: worker
      quantity: {{ .Values.nodepool.workercount }}
      unhealthyNodeTimeout: 0s
      workerRole: true
    machineGlobalConfig:
      cni: calico
