apiVersion: v1
name: rancher-cpi-vsphere-cluster-template
description: RKE2 CPI Cluster template for vSphere
version: 0.0.3
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default
